import argparse
import csv
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from a_star import AStar
from grid_loader import load_grid_scenario
from occupancy_grid import StochOccupancyGrid2D
from utils import snap_to_grid


SOLVER_MODES = ("vanilla", "modified")


def route_pair_key(x_init, x_goal):
    return (
        float(x_init[0]),
        float(x_init[1]),
        float(x_goal[0]),
        float(x_goal[1]),
    )


def build_occ_grid(scenario_name):
    occ, map_size, map_resolution = load_grid_scenario(scenario_name, plot=False)
    map_dim = [round(map_size[i] / map_resolution) for i in range(2)]
    occ_grid = StochOccupancyGrid2D(
        map_resolution,
        map_dim[0],
        map_dim[1],
        0,
        0,
        10,
        occ.T,
    )
    statespace_hi = snap_to_grid(map_size, map_resolution)
    return occ_grid, map_size, map_resolution, statespace_hi


def generate_random_free_point(occ_grid, rng):
    low = np.array([occ_grid.origin_x, occ_grid.origin_y], dtype=float)
    high = np.array(
        [
            occ_grid.origin_x + occ_grid.width * occ_grid.resolution,
            occ_grid.origin_y + occ_grid.height * occ_grid.resolution,
        ],
        dtype=float,
    )
    while True:
        xy = rng.uniform(low=low, high=high)
        x, y = occ_grid.snap_to_grid(xy)
        if occ_grid.is_free((x, y)):
            return (x, y)


def compute_path_length(path):
    if path is None or len(path) < 2:
        return 0.0
    total = 0.0
    for i in range(len(path) - 1):
        p0 = np.array(path[i], dtype=float)
        p1 = np.array(path[i + 1], dtype=float)
        total += float(np.linalg.norm(p1 - p0))
    return total


def compute_right_wall_distances(path, occ_grid, dist_thresh=15.0):
    dists = []
    if path is None or len(path) < 2:
        return dists
    for i in range(len(path) - 1):
        p0 = np.array(path[i], dtype=float)
        p1 = np.array(path[i + 1], dtype=float)
        step = p1 - p0
        norm = np.linalg.norm(step)
        if norm < 1e-9:
            continue
        travel_dir = step / norm
        dists.append(float(occ_grid.dist_to_wall_right(path[i + 1], travel_dir, dist_thresh=dist_thresh)))
    return dists


def compute_metrics(path, occ_grid, dist_thresh=15.0):
    path_length = compute_path_length(path)
    wall_dists = compute_right_wall_distances(path, occ_grid, dist_thresh=dist_thresh)
    if wall_dists:
        right_wall_avg = float(np.mean(wall_dists))
        right_wall_std = float(np.std(wall_dists))
    else:
        right_wall_avg = float("nan")
        right_wall_std = float("nan")
    return {
        "path_length": path_length,
        "right_wall_avg": right_wall_avg,
        "right_wall_std": right_wall_std,
        "num_wall_samples": len(wall_dists),
    }


def run_solver(mode, occ_grid, statespace_hi, x_init, x_goal, resolution):
    planner = AStar(
        [0, 0],
        statespace_hi,
        x_init,
        x_goal,
        occ_grid,
        resolution=resolution,
    )
    solved = planner.solve(mode=mode)
    if not solved:
        return None
    return planner.path


def summarize_by_solver(route_records):
    summary = {}
    for mode in SOLVER_MODES:
        lengths = np.array([r[mode]["path_length"] for r in route_records], dtype=float)
        wall_avgs = np.array([r[mode]["right_wall_avg"] for r in route_records], dtype=float)
        wall_stds = np.array([r[mode]["right_wall_std"] for r in route_records], dtype=float)

        summary[mode] = {
            "num_routes": int(len(route_records)),
            "path_length_mean": float(np.nanmean(lengths)),
            "path_length_std": float(np.nanstd(lengths)),
            "right_wall_avg_mean": float(np.nanmean(wall_avgs)),
            "right_wall_avg_std": float(np.nanstd(wall_avgs)),
            "right_wall_std_mean": float(np.nanmean(wall_stds)),
            "right_wall_std_std": float(np.nanstd(wall_stds)),
        }
    return summary


def load_resume_payload(path):
    resume_path = Path(path)
    if not resume_path.exists():
        raise FileNotFoundError(f"Resume file not found: {resume_path}")
    if resume_path.suffix.lower() != ".json":
        raise ValueError("Resume file must be a .json file generated by compare_astar.py")

    with resume_path.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    if "routes" not in payload or "config" not in payload:
        raise ValueError("Resume file is missing required keys: 'config' and/or 'routes'")
    if not isinstance(payload["routes"], list):
        raise ValueError("Resume file 'routes' must be a list")
    return payload


def validate_resume_compatibility(resume_payload, scenario, wall_dist_thresh):
    cfg = resume_payload.get("config", {})
    existing_scenario = cfg.get("scenario")
    existing_wall_thresh = cfg.get("wall_dist_thresh")
    existing_policy = cfg.get("failure_policy")
    existing_source = cfg.get("path_metric_source")

    if existing_scenario != scenario:
        raise ValueError(
            f"Resume scenario mismatch. Existing='{existing_scenario}', requested='{scenario}'."
        )
    if existing_policy != "resample_until_both_succeed":
        raise ValueError(
            "Resume file uses unsupported failure policy. Expected 'resample_until_both_succeed'."
        )
    if existing_source != "raw_path":
        raise ValueError("Resume file uses unsupported path metric source. Expected 'raw_path'.")
    if existing_wall_thresh is not None and float(existing_wall_thresh) != float(wall_dist_thresh):
        raise ValueError(
            f"Resume wall threshold mismatch. Existing={existing_wall_thresh}, requested={wall_dist_thresh}."
        )


def save_results(output_path, payload):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if output_path.suffix.lower() == ".json":
        with output_path.open("w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        return

    if output_path.suffix.lower() == ".csv":
        with output_path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "trial",
                    "x_init",
                    "x_goal",
                    "solver",
                    "path_length",
                    "right_wall_avg",
                    "right_wall_std",
                    "num_wall_samples",
                ],
            )
            writer.writeheader()
            for row in payload["routes"]:
                for solver in SOLVER_MODES:
                    metrics = row[solver]
                    writer.writerow(
                        {
                            "trial": row["trial"],
                            "x_init": row["x_init"],
                            "x_goal": row["x_goal"],
                            "solver": solver,
                            "path_length": metrics["path_length"],
                            "right_wall_avg": metrics["right_wall_avg"],
                            "right_wall_std": metrics["right_wall_std"],
                            "num_wall_samples": metrics["num_wall_samples"],
                        }
                    )
        return

    raise ValueError("Unsupported output format. Use .json or .csv")


def print_summary(summary, attempts, requested_routes):
    print("\n=== Comparison Summary ===")
    print(f"Requested paired routes: {requested_routes}")
    print(f"Sampling attempts: {attempts}")
    for mode in SOLVER_MODES:
        s = summary[mode]
        print(f"\n[{mode}]")
        print(f"  routes: {s['num_routes']}")
        print(f"  path_length mean/std: {s['path_length_mean']:.4f} / {s['path_length_std']:.4f}")
        print(f"  right_wall_avg mean/std: {s['right_wall_avg_mean']:.4f} / {s['right_wall_avg_std']:.4f}")
        print(f"  right_wall_std mean/std: {s['right_wall_std_mean']:.4f} / {s['right_wall_std_std']:.4f}")


def plot_sample_paths(occ_grid, sample_pairs, plot_output=None):
    if not sample_pairs:
        print("No sample paths available to plot.")
        return

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    if not isinstance(axes, np.ndarray):
        axes = np.array([axes])

    cmap = plt.get_cmap("tab10", max(len(sample_pairs), 1))
    for j, solver in enumerate(SOLVER_MODES):
        ax = axes[j]
        occ_grid.plot_grid(ax=ax)
        for i, sample in enumerate(sample_pairs):
            path = sample[f"{solver}_path"]
            xs, ys = zip(*path)
            color = cmap(i % cmap.N)
            label = f"trial {sample['trial']}"
            ax.plot(xs, ys, color=color, linewidth=1.4, alpha=0.85, label=label)
            ax.scatter(sample["x_init"][0], sample["x_init"][1], c=[color], s=12, zorder=5)
            ax.scatter(sample["x_goal"][0], sample["x_goal"][1], c=[color], marker="*", s=22, zorder=5)

        ax.set_title(f"{solver} ({len(sample_pairs)} paths)")
        ax.set_xlabel("X (m)")
        ax.set_ylabel("Y (m)")
        if len(sample_pairs) <= 10:
            ax.legend(loc="upper right", fontsize=8)

    fig.tight_layout()
    if plot_output:
        plot_path = Path(plot_output)
        plot_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(plot_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        print(f"Saved sample path figure to: {plot_output}")
    else:
        plt.show()


def run_experiment(
    scenario,
    num_routes,
    seed,
    output,
    max_attempts,
    wall_dist_thresh,
    resume_from=None,
    plot_samples=0,
    plot_output=None,
):
    rng = np.random.default_rng(seed)
    occ_grid, _, resolution, statespace_hi = build_occ_grid(scenario)

    records = []
    prior_attempts = 0
    start_trial = 1
    seen_pairs = set()
    if resume_from:
        prior_payload = load_resume_payload(resume_from)
        validate_resume_compatibility(prior_payload, scenario, wall_dist_thresh)
        records = list(prior_payload["routes"])
        prior_attempts = int(prior_payload.get("sampling_attempts", 0))
        start_trial = len(records) + 1
        for row in records:
            seen_pairs.add(route_pair_key(row["x_init"], row["x_goal"]))

    attempts = 0
    target_total_routes = len(records) + num_routes
    sample_pairs = []
    while len(records) < target_total_routes:
        attempts += 1
        if attempts > max_attempts:
            raise RuntimeError(
                f"Reached max attempts ({max_attempts}) before collecting {num_routes} new paired successful routes."
            )

        x_init = generate_random_free_point(occ_grid, rng)
        x_goal = generate_random_free_point(occ_grid, rng)
        if x_init == x_goal:
            continue
        pair_key = route_pair_key(x_init, x_goal)
        if pair_key in seen_pairs:
            continue

        vanilla_path = run_solver("vanilla", occ_grid, statespace_hi, x_init, x_goal, resolution)
        modified_path = run_solver("modified", occ_grid, statespace_hi, x_init, x_goal, resolution)
        if vanilla_path is None or modified_path is None:
            continue

        trial_num = len(records) + 1
        records.append(
            {
                "trial": trial_num,
                "x_init": [float(x_init[0]), float(x_init[1])],
                "x_goal": [float(x_goal[0]), float(x_goal[1])],
                "vanilla": compute_metrics(vanilla_path, occ_grid, dist_thresh=wall_dist_thresh),
                "modified": compute_metrics(modified_path, occ_grid, dist_thresh=wall_dist_thresh),
            }
        )
        seen_pairs.add(pair_key)
        if len(sample_pairs) < plot_samples:
            sample_pairs.append(
                {
                    "trial": trial_num,
                    "x_init": [float(x_init[0]), float(x_init[1])],
                    "x_goal": [float(x_goal[0]), float(x_goal[1])],
                    "vanilla_path": vanilla_path,
                    "modified_path": modified_path,
                }
            )

    summary = summarize_by_solver(records)
    print_summary(summary, attempts=prior_attempts + attempts, requested_routes=len(records))
    if resume_from:
        print(
            f"Resumed from {len(records) - num_routes} routes and added {num_routes} new paired successful routes "
            f"(trial {start_trial} to {len(records)})."
        )

    payload = {
        "config": {
            "scenario": scenario,
            "num_routes": len(records),
            "seed": seed,
            "max_attempts": max_attempts,
            "wall_dist_thresh": wall_dist_thresh,
            "failure_policy": "resample_until_both_succeed",
            "path_metric_source": "raw_path",
            "resumed_from": resume_from,
        },
        "sampling_attempts": prior_attempts + attempts,
        "summary": summary,
        "routes": records,
    }
    if output:
        save_results(output, payload)
        print(f"\nSaved results to: {output}")
    elif resume_from:
        save_results(resume_from, payload)
        print(f"\nSaved resumed results to: {resume_from}")

    if plot_samples > 0:
        plot_sample_paths(occ_grid, sample_pairs, plot_output=plot_output)


def parse_args():
    parser = argparse.ArgumentParser(description="Compare vanilla and modified A* on paired random start/goal routes.")
    parser.add_argument("--scenario", default="sample2_default", help="Grid scenario name from grid_scenarios.json")
    parser.add_argument(
        "--num-routes",
        type=int,
        required=True,
        help="Number of new paired successful routes to collect",
    )
    parser.add_argument("--seed", type=int, default=None, help="Random seed for reproducibility")
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional output file path (.json or .csv)",
    )
    parser.add_argument(
        "--max-attempts",
        type=int,
        default=None,
        help="Maximum random pair attempts before aborting (default: 100 * num_routes)",
    )
    parser.add_argument(
        "--wall-dist-thresh",
        type=float,
        default=30.0,
        help="Maximum right-wall search distance in meters",
    )
    parser.add_argument(
        "--resume-from",
        type=str,
        default=None,
        help="Path to a previous JSON output from compare_astar.py to continue from",
    )
    parser.add_argument(
        "--plot-samples",
        type=int,
        default=0,
        help="Number of new sample route pairs to plot side-by-side (vanilla vs modified)",
    )
    parser.add_argument(
        "--plot-output",
        type=str,
        default=None,
        help="Optional output image path for sample plot (e.g. samples.png); if omitted, shows figure",
    )
    args = parser.parse_args()
    if args.num_routes <= 0:
        raise ValueError("--num-routes must be > 0")
    if args.max_attempts is None:
        args.max_attempts = max(100, 100 * args.num_routes)
    if args.max_attempts <= 0:
        raise ValueError("--max-attempts must be > 0")
    if args.plot_samples < 0:
        raise ValueError("--plot-samples must be >= 0")
    return args


if __name__ == "__main__":
    cli = parse_args()
    run_experiment(
        scenario=cli.scenario,
        num_routes=cli.num_routes,
        seed=cli.seed,
        output=cli.output,
        max_attempts=cli.max_attempts,
        wall_dist_thresh=cli.wall_dist_thresh,
        resume_from=cli.resume_from,
        plot_samples=cli.plot_samples,
        plot_output=cli.plot_output,
    )
